#!/bin/bash
find md/ -name "*.md" -type f -exec sh -c 'markdown "$0" > "$0.html"' {} \;
cd md
rename.ul .md.html .html *.md.html
mv *.html ..
cd ..
find -name "*.html" -type f -exec sh -c 'cat "_atas.htm" "$0" "_bawah.htm" > "$0.trash"' {} \;
rm *.html
rename.ul .html.trash .html *.html.trash
echo "Happy Blogging :)"