blog = [
    "Manusia Itu Harus Bergerak, gerak.html",
    "Jangan Malas!, malas.html",
    "Menjalani Kehidupan dengan Fokus, jalan.html",
    "Makan Dikit, makan.html",
    "Kamu,&nbsp;Bertanggung Jawab Atas Dirimu Sendiri, tanggungjawab.html",
    "Saat Kita Kaya, kaya.html",
    "Ingin Didengar?, dengar.html",
    "Jangan (hanya) Mengeluh, mengeluh.html",
    "Takut Mencoba?, coba.html",
    "I love Github, git.html",
    "Organize Your Life!, organize.html",
    "Hari Pertama Ni..., pertama.html",
    "Karena Hidup adalah Kumpulan Cerita, cerita.html",
    "Pentingnya Keterampilan, terampil.html",
    "Mencoba Fokus, fokus.html",
    "Menebar Kemanfaatan, manfaat.html",
    "Hanya Mengkritik?, kritik.html",
    "Aturan Penggunaan Kuota, kuota.html",
    "Kau Pasti Bisa Melakukan Apapun, bisa.html",
    "Hari Baru!, newday.html",
    "Besok Harus Lebih Baik!, harus.html",
    "Karena Hidup Bukan Sekedar Menulis, tulisan.html",
    "Penghujung Ramadan yang Amat Berkesan, penghujung.html",
    "Mengapa Aku Memilih Statis Page Buat Blogging?, mengapa.html",
    "Hello World, hello.html",

    // catatan di isykarima
    "20/80, 2080.html",
    "Nama Kirito, kirito.html",
    "Trik Long March, triklongmarch.html",
    "Episode SAO, sao.html",
    "Harus Lebih Baik, baik.html",
    "Listrik Mati, mati.html",
    "Dewasa dan Keuangan, keuangan.html",
    "Harus Shaf Awal!, awal.html",
    "Dunia Khayalan, khayal.html",
    "Novel Memang Selalu Menarik, novel.html",
    "Life in Isykarima, lifeisyka.html"
]
